### ISSUE TITLE
1.10.2 - Unexpected error when right clicking on Grand Chair

### ISSUE THREAD

**Issue by viper2g1** [MrCrayfish/MrCrayfishFurnitureMod#109]
Hi, I compiled 1.10.2 against forge 12.18.1.2014.  I recieved the following error when right clicking the grand chair:

https://gist.github.com/viper2g1/769e824ec314f4e2755ea1f049b3050e

**Comment by SkyBlade1978** [comment]
Does it do the same whether you click on the upper or lower part of the chair?  I was just reading his code and I suspect the issue is in the item activation handler where if you lick on the upper part of the chair the method calls itself passing in a reference to the block below, triggering a null reference exception.

I'll try replicate it on my machine when I get some time, I'm not sure if MrCrayfish is active on this at the moment I can see your issue has been open a while!

**Comment by Hypsellis** [comment]
I get a crash too with Draconic Evolution when I try to sit me on a chair. http://pastebin.com/ird0MRS1

**Comment by Hypsellis** [comment]
MrCrayfish/MrCrayfishFurnitureMod#109

**Comment by MrCrayfish** [comment]
Fixed :)
