### ISSUE TITLE
Crash in server 1.11.2

### ISSUE THREAD

**Issue by ZOOM6969** [MrCrayfish/MrCrayfishFurnitureMod#131]
Do you have any prediction for the concert of this bug?

**Comment by Goldenowner** [comment]
I've been waiting 11 days, I wish MrCrayFish could release a new version with all the fixed bugs so far.

**Comment by MrCaira** [comment]
@ZOOM6969 & @Goldenowner I took the liberty to compile a new version from his latest releases on github, feel free to use this while you wait for an official release. [Download Link](https://www.dropbox.com/s/9y94gcimaei03ny/cfm-4.1.1-mc1.11.2_bugfixes.jar?dl=0)

**Comment by Goldenowner** [comment]
@MrCaira Thanks a lot!

**Comment by MrCaira** [comment]
@Goldenowner my testing this far have been successful, however i agree @MrCrayfish should be a lot better at prioritizing release. I'd strongly say that curses complete server shutdowns are so important to fix that it doesn't matter whether its a single bug or multi bug fix he makes. As long as people can use his mod at least especially since he has a patreon page where people can pay him to show support, he should show the same support towards his users..

**Comment by Goldenowner** [comment]
@MrCaira In single player I see all the item and can place them, but in Multiplayer I don't see any blocks/items in the furniture mod tab..

**Comment by MrCaira** [comment]
@Goldenowner what kind of server are you running with ? 

Default forge/vanilla server ?
And did you update both server and client version to the one i posted ?

**Comment by Goldenowner** [comment]
@MrCaira It all works perfectly now.

**Comment by MrCaira** [comment]
Here is my results, running on a "Sponge 1.11 Experimental" with forge build 2201   [http://imgur.com/a/kUnZo](http://imgur.com/a/kUnZo)

**Comment by MrCaira** [comment]
Ok never mind that last message then hehe 👍

**Comment by MrCrayfish** [comment]
Fixed. Download new update!
