### ISSUE TITLE
[1.10.2-4.1.2]  Sinks & Doorbell

### ISSUE THREAD

**Issue by plazticdagger** [MrCrayfish/MrCrayfishFurnitureMod#143]
Seems incredible hard to place both sinks in the direction wanted. Most of the time they turn to the right once placed. Sometimes they fill with water even though there is no water block below them when placing. 

Doorbell doesnt like to be placed correctly either. At times it will place opposite of the wall facing inward floating in air.

**Comment by Ashleyosity** [comment]
MC: 1.10.2 Furniture Mod V: 4.1.2
I too am having the same issues with doorbells, on servers specifically. They try to place floating at first, then flip around to the correct placement. Then when they're rang, they get flipped around again. This can be see here: https://youtu.be/YeU53Nv2Yq4?t=4m43s
Looking forward to the fix for this, I always add Furniture Mod to my modpacks.

**Comment by MrCrayfish** [comment]
I'm not sure I'll be support 1.10.2 anymore, however I have made a commit in 1.11.2 which fixes the issue. Check out this commit: 6adca00
