### ISSUE TITLE
Presents show up in all creative tabs

### ISSUE THREAD

**Issue by BrisingrAerowing** [MrCrayfish/MrCrayfishFurnitureMod#189]
You need to do something like [this](https://github.com/AlgorithmX2/Chisels-and-Bits/commit/fb38943bce9c30c09773f2b3b03036b147266960#diff-617810317411c8f3ddf74d4e39088abb) for your presents to prevent this.

EDIT: That uses the obfuscated name, for the MCP version you use the method is 'isInCreativeTab'

**Comment by AlgorithmX2** [comment]
This can also cause issues with other mods, https://github.com/AlgorithmX2/FlatColoredBlocks/issues/50

And is easily fixed by adding a new vanilla method call inside getSubItems
https://github.com/AlgorithmX2/Chisels-and-Bits/commit/fb38943bce9c30c09773f2b3b03036b147266960#diff-617810317411c8f3ddf74d4e39088abb

**Comment by MrCrayfish** [comment]
Apologises! I forgot to add this fix in. Will push a new version out quick

**Comment by MrCrayfish** [comment]
Thanks! Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/5bfed48c55ebad82f27ed3fbbbe0bf74bf7dc69c
