### ISSUE TITLE
Compatibility problem with the Sleeping Overhaul mod

### ISSUE THREAD

**Issue by Hackslider** [MrCrayfish/MrCrayfishFurnitureMod#413]
**Describe the bug**
If you use the Sleeping Overhaul mod with the Furniture mod together, the Sleeping Overhaul mod will not work anymore! That's because the Furniture mod does not expand the sleep system but replaces it! Would be nice if you could change that.
PS: Sorry for my bad english

Please complete the following information:
- Minecraft Version:1.12.2
- Mod Version:6.2.0

**Comment by MrCrayfish** [comment]
Show me in my code where it replaces the sleeping system?

**Comment by Hackslider** [comment]
I do not know the location in the code. I got that from comment # 45 from the SleepingOverhaul mod. Here's the link to the page: https://minecraft.curseforge.com/projects/sleepingoverhaul?gameCategorySlug=mc-mods&projectID=297284

**Comment by MrCrayfish** [comment]
Then why say "That's because the Furniture mod does not expand the sleep system but replaces it!". My mod uses the methods provided in the Block class to enabled sleeping in the Modern Bed, it doesn't do any special tricks to enabled it. If Sleeping Overhaul doesn't support those methods, then there is nothing I can do. You should contact the author to look into methods.
1. https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/blocks/BlockModernBed.java#L232
2. https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/blocks/BlockModernBed.java#L401
3. https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/blocks/BlockModernBed.java#L420
4. https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/blocks/BlockModernBed.java#L426
