### ISSUE TITLE
[suggestion] add support for pipes and ducts

### ISSUE THREAD

**Issue by seancrain** [MrCrayfish/MrCrayfishFurnitureMod#477]
I think it'd be a cool addition to connect sinks, toilets, showers, and bathtubs to a Buildcraft pipe system or Thermal Dynamics duct system to bring water into and out of the blocks, or possibly add a sewage liquid variant for dirty water.

**Comment by boot2big** [comment]
I'd agree, although probably not on the dirty water...

**Comment by dragonshardz** [comment]
It would be a nice QoL addition that would also work more reliably than trying to place infinite water sources underneath each fixture. Especially since fixtures don't seem to always recognize the water sources.

All that they need to be able to do is fill/unfill to a duct, conduit, other thing with a liquid inventory.

**Comment by landynmj** [comment]
Yes please!

**Comment by MrCrayfish** [comment]
It should now be possible with the latest version of the mod. The sink is now a fluid container.
