### ISSUE TITLE
[1.16.4] Mailboxes not showing up in post box

### ISSUE THREAD

**Issue by Scwestbrook** [MrCrayfish/MrCrayfishFurnitureMod#638]
**Describe the bug**
When I place down a mailbox and a post box, and I open the post box, nothing ever shows up in the list.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place a mailbox
2. Place down a post box

**Screenshots**
**No screenshots are applicable**
Please complete the following information:
- Minecraft Version: Forge 1.16.4
- Mod Version: 7.0.0
Also, bug is present in 1.16.5 too

**Comment by samdev-7** [comment]
Same issue here

**Comment by Anan986** [comment]
Same issue with me

**Comment by Scwestbrook** [comment]
Is this going to get fixed??

**Comment by MrCrayfish** [comment]
I can't seem to reproduce. Anyone got specific details on how to reproduce. Is it only on a server? Are you in a different dimension? Have you got other mods installed? Does this work if no mods expect the furniture mod installed?

**Comment by samdev-7** [comment]
Tried on latest with 1.16.5

There is optifine
Does not work on singleplayer and multiplayer.
In overworld.

**Comment by MrCrayfish** [comment]
Are you using any extra mods?

**Comment by MrCrayfish** [comment]
@SamL2020 Are you using any extra mods? Does it work without mods installed expect the furniture mod? (Like mentioend in previous comment)

**Comment by Anan986** [comment]
Yes we are using extra mods

**Comment by MrCrayfish** [comment]
This issue is currently not progressing. If someone wants to help please do the following:
1. Verify you are using the absolute latest version of the Furniture Mod (should be 7.0.0-pre19 and downloaded only from CurseForge or my website mrcrayfish.com)
2. List all the mods you currently have installed
3. Does the issue occur on singleplayer and/or multiplayer? If multiplayer, are you using custom server software and which one?
4. Can you test if the issue happens if only the furniture mod is installed? If you have Optifine, test with and without.
5. Send the start up logs of your game? For safe measure, send latest.log and debug.log (Located in your .minecraft folder, inside the logs folder)

Thank you

**Comment by samdev-7** [comment]
> @SamL2020 Are you using any extra mods? Does it work without mods installed expect the furniture mod? (Like mentioend in previous comment)

I am not using extra mods, though I will try again with a newer forge version.

**Comment by Scwestbrook** [comment]
I'm using no other mods, but I will try again. I downloaded from mrcrayfish.com. Also, I love your redstone tutorials, they allowed my friend to build with redstone, they couldn't before!

**Comment by Scwestbrook** [comment]
The issue seems to be simply that the mailboxes don't show up, but can be sent to in the GUI

**Comment by Scwestbrook** [comment]
Also, the issue occurred with and without other mods, but here are my logs with  the Create mod:
<a href="https://gist.github.com/Scwestbrook/ce6120429203a09f3ac49859d9be8e2c"> debug.log</a>
<a href="https://gist.github.com/Scwestbrook/38e6d073caceca1acfb965e26e193473"> startup.log </a>

**Comment by MrCrayfish** [comment]
> The issue seems to be simply that the mailboxes don't show up, but can be sent to in the GUI

Can you send a screenshot of the GUI? Based on my code, to send items to the mailboxes it would need to be rendering in the list.

Also because this issue is becoming stale again, I will have a custom version of the furniture mod I will post here that will have debugging information that will hopefully help resolve the issue. I just can't reproduce this issue.

**Comment by XBagon** [comment]
Content of the Stripped Warped Mail Box and all other Nether Wood Mail Boxes still isn't shown.
