### ISSUE TITLE
Missing Items in 1.16.1

### ISSUE THREAD

**Issue by irondragon12** [MrCrayfish/MrCrayfishFurnitureMod#646]
for some reason i dont see the kitchen stuff. for example, blender, toaster, and all kitchen stuff related to those. i did find one thing about the 1.15.1 version saying that u are revamping or something the mod. if that is true why is there still none of those items? plus there is a 1.16.3 version. so can you or someone plz tell me if they will ever be added back or what is wrong?

**Comment by sweathers** [comment]
It looks like many of the furniture blocks from 1.12 are not included yet in the latest jars (1.15, 1.16)  Are there plans to include those older blocks (Bath, Shower, etc) in the newer versions?  
Could you provide a list of the blocks that should be in each version so that we know what to expect in each?
