### ISSUE TITLE
[Minecraft 1.12.2] Mirror renders a block higher

### ISSUE THREAD

**Issue by Von6** [MrCrayfish/MrCrayfishFurnitureMod#647]
When placing down the mirror block the reflection is a block higher

![2021-01-10_09 29 18](https://user-images.githubusercontent.com/77242387/104130595-6c8d6300-5326-11eb-89da-2dd5933aa6ee.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by InuYasha86000** [comment]
was there ever a fix either found or made for 1.12.2 for this?

**Comment by MrCrayfish** [comment]
@InuYasha86000 No. Please use a modern verison

**Comment by InuYasha86000** [comment]
unfortunetly that's not an option at this time as it's part of my modpack which due to the vast majority of mods being stalled on 1.12.2 I cannot update to a newer mc version of the mod.
thank you for the speedy reply though, it's always good to see a mod author that is willing to reply fairly quick.
