### ISSUE TITLE
[1.15.2-31.2.49] All curtains are white, Please add back shower and other stuff taken out!!

### ISSUE THREAD

**Issue by CookieCraver** [MrCrayfish/MrCrayfishFurnitureMod#669]
Any curtains, no matter what colors, turn white after being placed. Also please bring back all the stuff you took out!! Even if your updating the mod items or texture why take it out completely until you do? It just makes things suck for the people who love this mod and everyone I knew was sad and disappointed. 

Please complete the following information:
- Minecraft Version:1.15.2-31.2.49 forge
- Mod Version:any prev(even 1.12.2)-pre16

**Comment by Autovw** [comment]
1.12.2 is both unsupported by Forge & MrCrayfish so he most likely won't fix this issue.

Because 1.13 has changed a lot of code for the game It's not possible to just add the old furniture back so the entire mod needs to be rewritten, which is a lot of work and Cray can't dedicate all of his time to modding.
So that might take a while. :)
