### ISSUE TITLE
[Suggestion] Use block inheritence textures for mod compatibility

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/MrCrayfishFurnitureMod#758]
The Mantle library Tinker's Construct uses has a feature that allows recipes to effectively copy the texture of the referenced block and use it as the base for crafted items (in their case the wooden parts of crafting stations), as documented here: https://github.com/SlimeKnights/Mantle/wiki/Recipe-Serializers#shaped-retextured  
This allows their decorative blocks to natively support any mod's wood without needing to add countless duplicate recipes.  

It may be worthwhile to look into how such an approach could be applied to the furniture in this mod to allow support for mods that add new wood types.

**Comment by MrCrayfish** [comment]
It's a cool idea. I have definitely thought about dynamic textures in the Furniture Mod. One problem with this feature is that it's major change that would break worlds and adds additional overhead since blocks have to become block entities to retain the texture data. For now I recommend using https://www.curseforge.com/minecraft/mc-mods/every-compat
